---
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: workshop-argocd
spec:
  grafana:
    enabled: true
    route:
      enabled: true
  prometheus:
    enabled: true
    route:
      enabled: true
  server:
    route:
      enabled: true
  rbac:
    defaultPolicy: 'role:readonly'
    policy: |
      g, system:cluster-admins, role:admin
...
