---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-infra 
  namespace: argocd
spec:
  project: default 
  source:
    repoURL: https://github.com/darthlukan/gitops-workshop.git
    targetRevision: HEAD
    path: sample-infra 
  destination:
    # Need to get this automagically via detection
    server: https://kubernetes.default.svc
    namespace: sample-infra 
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  syncPolicy:
    automated:
      selfHeal: true
...
