apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: build-increment-merge
spec:
  tasks:
  - name: git-clone
    taskRef:
      name: git-clone
    params:
      - name: url
        value: $(params.repo-url)
      - name: revision
        value: $(params.git-branch) 
    workspaces:
      - name: output
        workspace: git-clone-output
  - name: build-image
    taskRef:
      name: buildah
    params:
      - name: IMAGE
        value: $(params.image-name) 
      - name: DOCKERFILE
        value: $(params.workspace.git-clone-output.path)/Dockerfile
    workspaces:
      - name: gitops-workshop-repo-source 
        persistentVolumeClaim:
          claimName: git-clone-output
