apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: build-increment-merge
spec:
  resources:
  - name: app-repo
    type: git
  - name: app-image
    type: image
  params:
  - name: deployment-name
    type: string
    description: name of the deployment to be patched
  tasks:
  - name: build-image
    taskRef:
      name: build-image
      kind: Task
  # TODO
  # - name: increment-version
    # taskRef:
      # name: increment-version
    # runAfter:
    # - build-image
  # - name: git-merge
    # taskRef:
      # name: git-merge
    # runAfter:
    # - increment-version