apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: gitops-workshop-pipeline-run-
  namespace: gitops-workshop
spec:
  serviceAccountName: build-bot
  pipelineRef:
    name: build-increment-merge
  workspaces:
    - name: gitops-workshop-repo-source
      persistentVolumeClaim:
        claimName: git-clone-output
  params:
    - name: repo-url
      value: https://github.com/darthlukan/gitops-workshop.git
    - name: git-branch
      value: master
    - name: image-name
      value: quay.io/sscaling/my-image
    - name: app-path
      value: gitops-workshop/sample-app