---
- name: Setup Workshop
  hosts: local
  tasks:
  - import_role:
      name: darthlukan.argocd_install.install_prereqs

  - import_role:
      name: darthlukan.argocd_install.install_argocd

  - name: Deploy workshop ArgoCD cluster
    k8s:
      namespace: argocd
      src: "{{ playbook_dir }}/files/workshop-argo-cluster-cr.yaml"
      state: present
      kubeconfig: "{{ kubeconfig }}"
...
