---
- name: Setup Workshop
  hosts: local
  tasks:
  - import_role:
      name: darthlukan.argocd_install.install_prereqs

  - import_role:
      name: darthlukan.argocd_install.install_argocd

  - name: Create Pipelines Operator Subscription
    k8s:
      definition:
        apiVersion: operators.coreos.com/v1alpha1
        kind: Subscription
        metadata:
          name: openshift-pipelines-operator
          namespace: openshift-operators
        spec:
          channel:  ocp-4.4
          name: openshift-pipelines-operator-rh 
          source: redhat-operators 
          sourceNamespace: openshift-marketplace 

  - name: Deploy workshop applications
    k8s:
      namespace: argocd
      src: "{{ playbook_dir }}/files/{{ item }}"
      state: "{{ state }}"
      kubeconfig: "{{ kubeconfig }}"
    loop:
      - workshop-argo-cluster-cr.yaml
      - workshop-argo-project-cr.yaml
      - workshop-sample-app-cr.yaml
      - workshop-sample-infra-cr.yaml
      - workshop-sample-app-ci-cr.yaml
    when: state == 'present'
...
