---
- name: Setup Secrets
  hosts: local
  tasks:
    - name: Create GitHub Secret
      k8s:
        state: present
        definition: "{{ lookup('file', 'github-secret.yaml') }}"
        
    - name: Patch ServiceAccount Secrets
      k8s:
        definition:
          apiVersion: v1
          kind: ServiceAccount
          metadata:
            name: pipeline
            namespace: gitops-workshop
          secrets:
            - name: github-token-secret
...
