---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-cicd-to-namespace
  namespace: sample-app
spec:
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            app.kubernetes.io/instance: sample-app-cicd
        podSelector: {}
...
